# Entradas & Snacks Salgados {.unnumbered}

## Guacamole {.unnumbered}

**Fonte:** Gastrotecnia

{Foto}

**Tempo:**

**Porções:**

**Dificuldade:**

**Avaliação:**

### Ingredientes {.unnumbered}

-   1 abacate maduro
-   1 tomate
-   ½ cebola pequena
-   ½ limão
-   1 c. café rasa sal
-   1 c. sobremesa azeite

### Preparação {.unnumbered}

1.  Cortar o abacate ao meio e com uma colher retirar toda sua polpa e descartar a semente.
2.  Colocar esta polpa numa tigela grande e esmagar com um garfo. Reservar.
3.  Após lavar o tomate, retirar a pele e as sementes, picar em cubos pequenos e juntar ao abacate.
4.  Descascar a cebola, cortar em cubos muito pequenos e juntar ao abacate.
5.  Misturar tudo, temperar com o sumo de limão, sal e azeite.
6.  Servir de imediato ou conservar no frigorífico (2 dias).

## Húmus de Beterraba {.unnumbered}

**Fonte:** Gastrotecnia

{Foto}

**Tempo:**

**Porções:**

**Dificuldade:**

**Avaliação:**

### Ingredientes {.unnumbered}

-   200 g grão-de-bico já cozido
-   1 beterraba já cozida
-   1 dente alho
-   10 g Azeite
-   q.b. pimenta preta

### Preparação {.unnumbered}

1.  Num recipiente, junte o grão-de-bico, a beterraba, o azeite, o dente de alho (cru) e a pimenta preta.
2.  Triture a mistura com varinha mágica na velocidade máxima até obter consistência de pasta.
3.  Servir de imediato ou conservar no frigorífico (2 dias).

## Húmus de Pimentos {.unnumbered}

**Fonte:** Gastrotecnia

{Foto}

**Tempo:**

**Porções:**

**Dificuldade:**

**Avaliação:**

### Ingredientes {.unnumbered}

-   200 g grão-de-bico já cozido
-   1 pimento vermelho
-   2 dentes alho
-   10 g Azeite
-   ½ limão
-   ½ c. chá pimentão doce
-   q.b. pimenta preta

### Preparaçã {.unnumbered}

1.  Lavar bem o pimento e descascar os dentes de alho.
2.  Num tabuleiro de forno, dispor o pimento cortado em quartos e os dentes de alho.
3.  Temperar com um fio de azeite.
4.  Assar no forno a 180ºC, durante 20-30 minutos.
5.  Após arrefecer, retire a pele do pimento.
6.  Num recipiente, junte o grão-de-bico, o sumo do limão, o pimento assado e os dentes de alho (assados), o pimentão doce e a pimenta preta.
7.  Triture a mistura com varinha mágica na velocidade máxima até obter consistência de pasta.
8.  Servir de imediato ou conservar no frigorífico (2 dias).